### ISSUE TITLE
Prototype One

### ISSUE THREAD

**Issue by joeyisok** [STG-source/GrassJellyDatePrinting#2]
Due 5/5/2017

**Comment by joeyisok** [comment]
@Chayes2017 สามารถ download [POSAssist Jummy](https://goo.gl/rCn4sf) ได้เลยครับ

**Comment by joeyisok** [comment]
Job Detail Memo 2/5/2017
![image](https://cloud.githubusercontent.com/assets/14802508/25645887/0077f9b6-2fdd-11e7-91a1-dda5f8a4efef.png)

**Comment by Chayes2017** [comment]
Progress ล่าสุดที่กำลังปรับปรุงแต่ยังไม่ได้อัพเดท Source ครับ
![1493837534245](https://cloud.githubusercontent.com/assets/28284479/25676607/d71a29c8-306c-11e7-886f-118dc552427e.jpg)

**Comment by joeyisok** [comment]
@Chayes2017  เยี่ยมครับ
ในส่วนของ UI ปุ่ม "กำหนดเอง" ช่องจำนวนวัน ช่วยปรับให้เลขที่ (ในตัวอย่างคือเลข 1) ให้ชิดขวาด้วยครับ
จำนวนดวงที่พิมพ์ด้วยเหมือนกันครับ

**Comment by Chayes2017** [comment]
ตอนนี้ตรวจพบว่า คำสั่งที่ใช้พิมพ์สติ๊กเกอร์ คำสั่ง  printLabel(prnText:String = null):void ใน POSAssist.as
ที่มีการใช้ข้อความที่กำหนดขึ้นต้นด้วย \vPRINT_LABEL มีการกำหนดตำแหน่งของข้อความเอาไว้ข้างใน POSAssist (JUMMY) ก่อนแล้ว ทำให้ไม่สามารถพิมพ์ตาม Format วันหมดอายุข้างล่างได้

ผลิต dd/mm/yy
หมดอายุ dd/mm/yy

ผลลัพท์การพิมพ์ลงสติ๊กเกอร์ โดยทดสอบใส่ตัวเลข 001 เพิ่มเติมในบรรทัดแรก
![default](https://cloud.githubusercontent.com/assets/28284479/25710352/36836d30-3116-11e7-8306-9d54c0e890f9.png)
[Sticker.pdf](https://github.com/STG-source/GrassJellyDatePrinting/files/976565/Sticker.pdf)

**Comment by joeyisok** [comment]
@Chayes2017 ต้องการให้ test กับ doPDF ด้วยการ printing ข้อความภาษาไทยครับ

**Comment by Chayes2017** [comment]
Note :

1. เพิ่ม Reset Button
2. ปรับขนาดตัวอักษรให้ใหญ่ขึ้น และ ทำให้ UI เต็มหน้าจอสัมผัส (ที่คิดเอาไว้คือ ขนาด 1024 x 768)
3. บล็อกปุ่มพิมพ์ไม่ให้มีการกดซ้ำได้จนกว่าจะพิมพ์เสร็จ หรือได้สั่งยกเลิกไปแล้ว
4. เพิ่ม Counter ลงสติ๊กเกอร์เพื่อดูว่าพิมพ์ไปแล้วกี่ชุด

**Comment by Chayes2017** [comment]
เพิ่มการบล๊อกปุ่มเมื่อสั่งพิมพ์


ปัญหาที่พบ
Symptom
เมื่อปุ่มพิมพ์มีการ Enable แล้วและรีบกดขณะที่สติ๊กเกอร์ยังพิมพ์อยู่ ทำให้พบปัญหาสติ๊กเกอร์อันแรกหายไป
![20170505_174207](https://cloud.githubusercontent.com/assets/28284479/25742735/0a33c428-31bb-11e7-9b10-fb9e8b7366c9.jpg)

สาเหตุ
การพิมพ์สติ๊กเกอร์คือการส่งสัญญาณไปที่ POSAssist และใช้วิธีหน่วงเวลาพิมพ์โดยไม่ได้รอสัญญาณตอบกลับจากเครื่องพิมพ์
เมื่อ Timer นับจำนวนลูปครบจึงจะ Enable ปุ่ม แต่เครื่องพิมพ์ยังทำงานอยู่ ทำให้เมื่อสั่งพิมพ์อีกครั้งขณะที่เครื่องพิมพ์ยังไม่เสร็จ ทำให้เกิดปัญหานี้ขึ้นได้

Note
ไม่พบปัญหาสติ๊กเกอร์พิมพ์ไม่ครบ ถ้ารอให้เครื่องพิมพ์ได้พิมพ์สติ๊กเกอร์ดวงสุดท้ายก่อนกดสั่งพิมพ์

**Comment by Chayes2017** [comment]
วิธีแก้ปัญหาสติ๊กเกอร์พิมพ์ไม่ครบ (อันแรกไม่พิมพ์ออกมา) คือ หลังจากพิมพ์ทุกดวงเสร็จแล้วให้หน่วงเวลาเพิ่มอีก 1 วินาทีเพื่อรอให้เครื่องพิมพ์สติ๊กเกอร์พิมพ์หมดก่อน จึงจะเริ่มทำงานได้

อัพเดท #2 เพิ่มการบล็อกการพิมพ์ ไม่ให้กดซ้ำจนกว่าเครื่องพิมพ์จะพร้อมใช้งาน

Note : Todo

- [x] 1.     เพิ่ม Reset Button
- [x] 2.     ปรับขนาดตัวอักษรให้ใหญ่ขึ้น และ ทำให้ UI เต็มหน้าจอสัมผัส (ที่คิดเอาไว้คือ ขนาด 1024 x 768)
- [x] 3.     บล็อกปุ่มพิมพ์ไม่ให้มีการกดซ้ำได้จนกว่าจะพิมพ์เสร็จ
- [x] 4.     เพิ่มปุ่มสั่งยกเลิกการพิมพ์
- [x] 5.     เพิ่ม Counter ลงสติ๊กเกอร์เพื่อดูว่าพิมพ์ไปแล้วกี่ชุด

**Comment by Chayes2017** [comment]
ปรับขนาด UI

- เพิ่มปุ่มล้างค่า  ล้างแล้วสติ๊กเกอร์จะเป็นค่า 0
- ปรับค่า Default ของจำนวนสติ๊กเกอร์ให้เป็น 0 เมื่อเปิดโปรแกรม
- ปรับปุ่มสั่งพิมพ์ให้ไม่สามารถสั่งพิมพ์สติ๊กเกอร์จำนวน 0 ได้

รูปภาพ App แบบเต็มหน้าจอ
![default](https://cloud.githubusercontent.com/assets/28284479/25746143/4b24d68c-31cc-11e7-8833-be518f76b1d4.png)

**Comment by joeyisok** [comment]
@Chayes2017 จากตัวอย่างสั่งพิมพ์ 05/05/2017 แล้วทำไม
ถึงพิมพ์ออกมาเป็น "05/00/17" ครับ?
วันหมดอายุก็ด้วยครับ

**Comment by joeyisok** [comment]
- [ ]  4. เพิ่มปุ่มสั่งยกเลิกการพิมพ์
ตามที่แจ้งมา อันนี้จะยกเลิกยังไงเหรอครับ?

**Comment by Chayes2017** [comment]
ผมตรวจสอบพบบัคใน Format เดือนครับ

ผมได้ใช้ Format dd/mm/yy  ผมเปลี่ยนมาใช้เป็น dd/MM/yy แทนแล้วครับ

![image](https://cloud.githubusercontent.com/assets/28284479/25770742/07003536-3268-11e7-94cd-64c1d8cd337e.png)

[Sticker Month Bug fixed.pdf](https://github.com/STG-source/GrassJellyDatePrinting/files/980765/Sticker.Month.Bug.fixed.pdf)

**Comment by Chayes2017** [comment]
จากคำถาม
4. เพิ่มปุ่มสั่งยกเลิกการพิมพ์
ตามที่แจ้งมา อันนี้จะยกเลิกยังไงเหรอครับ?

ถึงคุณ @joeyisok ปุ่มยกเลิกใช้สำหรับหยุดพิมพ์สติ๊กเกอร์ ด้วยเหตุผลเรื่องการเลือกวันผลิตย้อนหลังหรืออายุสินค้าผิด และได้สั่งพิมพ์หลายร้อยชิ้น จึงควรมีปุ่มใช้สำหรับยกเลิกครับ

**Comment by joeyisok** [comment]
@Chayes2017 กรณีถ้าสั่งหยุด หมายถึงว่าถ้าสั่งพิมพ์ 100 ดวง แล้วกำลังพิมพ์ดวง 10 อยู่ สามารถหยุดการพิมพ์ดวงที่เหลือได้ทันทีเลยใช่มั้ยครับ?

**Comment by Chayes2017** [comment]
ถึงคุณ @joeyisok

ใช่ครับ  ตอนนี้อัพเดทล่าสุดเพิ่มปุ่ม Button ที่สามารถหยุดการพิมพ์สติ๊กเกอร์ดวงที่เหลือได้ครับ

**Comment by Chayes2017** [comment]
อัพเดทล่าสุดมีการ marge , แก้ฟังก์ชั่น + variable ใน POSAssist.as ให้ถูกต้อง , แก้การตั้งชื่อ package และ class แล้วครับ

**Comment by Chayes2017** [comment]
ผลการทดสอบจับเวลาพิมพ์สติ๊กเกอร์ด้วยการอ่าน Log ตอนสั่ง Run โปรแกรม

1 ดวง = 0.501 วินาที
100 ดวง = 51 วินาที
150 ดวง = 1 นาที 18 วินาที
500 ดวง = 4 นาที 11 วินาที
1000 ดวง = 8 นาที 23 วินาที

**Comment by Chayes2017** [comment]
พบปัญหาเมื่อใช้โปรแกรมพิมพ์สติ๊กเกอร์เวอร์ชั่นล่าสุดแล้วทดสอบการพิมพ์ที่ระดับ 200 ms / 1 ดวง รอบละ 10 ดวง สองครั้ง และ 2 ชุด ทำให้เครื่องพิมพ์ไม่สามารถพิมพ์สติ๊กเกอร์ได้ครบจำนวน 40 ดวงได้

![20170511_111652](https://cloud.githubusercontent.com/assets/28284479/25933330/fbd7b644-363f-11e7-81c3-9b8730115de1.jpg)

**Comment by Chayes2017** [comment]
ทดสอบจับเวลากับเครื่องพิมพ์ Brother MFC-J430W Printer สติ๊กเกอร์ขนาด 8 x 20mm. ชุดละ 150 ดวง พิมพ์ 6 ชุด (ใช้ MS Word) ใช้เวลาต่อไปนี้

900 ดวง ใช้เวลา 2 นาที 30 วินาที
1 ดวง     ใช้เวลา 0.166 วินาที => 166 มิลลิวินาที 

เทียบกับเครื่องพิมพ์สติ๊กเกอร์ทีละอัน พิมพ์ได้ 1 ดวงต่อ .502 มิลลิวินาที
ผลลัพท์   เครื่องพิมพ์สติ๊กเกอร์ BIRCH ใช้เวลาพิมพ์ (ที่เสถียร) นานกว่า Brother MFC-J430W Printer 
3.02 เท่า

**Comment by Chayes2017** [comment]
พบสิ่งที่ต้องปรับปรุงเพิ่มเติม

- [x] ตรวจหา Error สามบรรทัดที่เกิดขึ้นใน log และแก้ไข
- [x] เปลี่ยนวิธี Connect และ Disconnect เฉพาะตอนที่พิมพ์และหลังพิมพ์เสร็จ เปลี่ยนเป็น ให้ Connect ตลอดเวลา , Disconnect ตอนปิดโปรแกรมเท่านั้น และ ปรับให้ Connect เองทันทีที่เกิดการ Disconnect ขึ้น
- [x] ปรับ Date Calendar ที่ Disable (วันหมดอายุ) ให้เป็น TextInput ธรรมดาเท่านั้น
- [x] พบ Exception ในฟังก์ชั่นการ Cancel สติ๊กเกอร์
- [x] คำสั่งยกเลิกการพิมพ์ห้ามใช้คำว่า Fail ใน log ให้ใช้คำว่า Cancel แทน
- [x] ปรับให้ระบบแจ้งเตือนเมื่อ POSAssist เกิดการ Disconnect และยกเลิกการแจ้งเตือนเมื่อ Connect สำเร็จ
- [x] จับเวลาพิมพ์สติ๊กเกอร์ 750 ดวง (5 แผ่น) ด้วยเครื่อง Brother MFC-J430W Printer และเทียบเวลากับเครื่องพิมพ์สติ๊กเกอร์ BIRCH

**Comment by Chayes2017** [comment]
อัพเดทล่าสุดมีการแก้ไขปัญหาด้วยวิธีการต่อไปนี้

1. Error สามบรรทัดที่เกิดขึ้นเกิดจากการแปลงค่าด้วยคำสั่ง as เช่น obj as ToggleButton จะทำให้ได้ค่า null กลับมาและโปรแกรมแจ้ง Error เพราะเรียกใช้ตัวแปรค่า null (แก้โดยตรวจสอบชนิดข้อมูลก่อนนำไปใช้)

2. เปลี่ยนวิธี Connect โดยให้ Connect ตลอดเวลา , Disconnect ตอนปิดโปรแกรมเท่านั้น และ ปรับให้ Connect เองทันทีที่เกิดการ Disconnect ขึ้น (ถ้า Disconnect จะสั่ง Timer อัตโนมัติเพื่อวนลูปเชื่อมต่อทุก ๆ 1 วินาที)

3. Exception ในฟังก์ชั่นการ Cancel สติ๊กเกอร์เกิดจากใช้งาน Object ที่มีค่า null แก้โดยตรวจสอบ Object ก่อนนำไปใช้

4. แก้คำว่า Fail เป็น Cancel ใน log เมื่อสั่งยกเลิกการพิมพ์สติ๊กเกอร์
5. ปรับให้ระบบแจ้งเตือนเมื่อไม่มีการเชื่อมต่อกับ POSAssist  โดยขึ้นคำว่า "ไม่ได้เชื่อมต่อ POSAssist"

สิ่งที่กำลังปรับแก้ไข
- ปรับ Date Calendar ที่ Disable (วันหมดอายุ) ให้เป็น TextInput ธรรมดาเท่านั้น

**Comment by Chayes2017** [comment]
อัพเดทล่าสุด [9f022e3](https://github.com/STG-source/GrassJellyDatePrinting/commit/9f022e3782413a6b1ad302c0ed7274a1036b22a7) มีการแก้ไขปัญหาเรื่องการปรับ Date Calendar ที่ Disable (วันหมดอายุ) ให้เป็น TextInput ธรรมดาเท่านั้น

Note เพิ่มเติม :
ตรวจสอบพบว่า DateFieldTH มีการ Extend จาก DateField และใน component ตัวนี้มี Object สามชนิด หนึ่งในนั้นคือ TextInput , Object หลัก , Button

ส่วนของ Button คือปุ่ม UI ที่ต้องการปิดใช้งาน
ส่วนของ TextInput คือส่วนแสดงข้อความที่ยังคงแสดงข้อความ

ดังนั้น commit ล่าสุดแก้ไขโดย Disable และ ทำการ Invisible กับส่วนที่เป็น Button ออกไป

**Comment by Chayes2017** [comment]
จากการทดสอบกับเครื่องพิมพ์ BIRCH BP 525D โดยทดสอบดังต่อไปนี้

1. กดปุ่มพิมพ์ติดต่อกันหลายที ครั้งละ 3 ใบ
2. ทดสอบพิมพ์ 10 ใบแล้วสั่งหยุด และทดสอบพิมพ์อีกครั้งเพื่อดูความต่อเนื่องและความถูกต้องของสติ๊กเกอร์
3. ตรวจสอบ Log ที่เกิดขึ้นผ่าน trace() เพื่อดู Exception หรือ Error ต่าง ๆ โดยเปิดการใช้งาน trace() เต็มรูปแบบจาก commit ก่อนหน้า

สรุปผลการทดสอบ

จากการพิมพ์ต่อเนื่องจากข้อ 1 ถึง 3 พบ Error ตามรูป 1 ครั้ง ทำให้เครื่องพิมพ์หยุดทำงาน และจำเป็นต้องปิดและเปิด POSAssist ใหม่อีกครั้ง
![default](https://cloud.githubusercontent.com/assets/28284479/25981573/3fb0f87e-3700-11e7-9c3a-d0809467b256.png)

นอกเหนือจากปัญหาข้างบนแล้ว ลำดับการพิมพ์ , วันเดือนปีของวันหมดอายุ และวันผลิตมีความถูกต้อง

**Comment by Chayes2017** [comment]
## ลักษณะและหน้าตาของโปรแกรมใน Commit ล่าสุด [9f022e3](https://github.com/STG-source/GrassJellyDatePrinting/commit/9f022e3782413a6b1ad302c0ed7274a1036b22a7) 

วิธีการใช้งานโดยอิงตามรูปภาพข้างล่าง :
เลือกวันที่เริ่มผลิตสินค้า => เลือกอายุสินค้า => เลือกจำนวนสติ๊กเกอร์ => สั่งพิมพ์
![default](https://cloud.githubusercontent.com/assets/28284479/25981787/608ce6c4-3701-11e7-8c88-eb64b3f13a5c.png)



การแจ้งเตือน

เมื่อสั่งพิมพ์โดยไม่เปิดใช้งาน POSAssist จะมีการแจ้งเตือนให้ทราบว่า ไม่ได้เชื่อมต่อ POSAssist เมื่อพยายามจะพิมพ์โดยไม่ได้เปิดโปรแกรม POSAssist
![default](https://cloud.githubusercontent.com/assets/28284479/25981739/270d893a-3701-11e7-87c1-dd9a1c6e6794.png)


## สิ่งที่น่าจะปรับปรุงเพิ่มเติมอีก
1. Progress ของการพิมพ์ เช่น Counter ที่พิมพ์ไปแล้ว , Count down ของจำนวนสติ๊กเกอร์ที่กำลังพิมพ์ หรือแท่ง Progress จาก 0% ถึง 100%  ดังนั้นถ้ามีการยกเลิกสติ๊กเกอร์ ตัว Counter หรือ Progress จะถูก Reset ตามไปด้วย
2. น่าจะมีระบบที่รองรับการ Pause และ Resume เครื่องพิมพ์โดยเริ่มพิมพ์ต่อจากจำนวนที่เหลือ

**Comment by joeyisok** [comment]
@Chayes2017 
Well Done & Thank you so much krub +1:

**Comment by joeyisok** [comment]
> น่าจะมีระบบที่รองรับการ Pause และ Resume เครื่องพิมพ์โดยเริ่มพิมพ์ต่อจากจำนวนที่เหลือ

Act in issue #10 krub
